# Generated by Django 3.1.4 on 2021-01-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_defaultcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultcontact',
            options={'verbose_name': 'Default Contact', 'verbose_name_plural': 'Default Contacts'},
        ),
    ]
