# Generated by Django 3.1.2 on 2020-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='boyi',
            field=models.PositiveIntegerField(default=0, verbose_name="Bo'yi"),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='*'),
        ),
    ]
