# Generated by Django 3.1.2 on 2020-12-03 13:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201202_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='About Actor'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='karyera',
            field=models.TextField(verbose_name='karyera'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='Yangilik nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('desc', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='movie/', verbose_name='Yangilik rasmi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='post sanasi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
