# Generated by Django 3.1.5 on 2021-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201207_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dizlikes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ko`rildi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ko`rildi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ko`rildi'),
        ),
    ]
